const avengers = [
  { id: 0, name: "Thor" },
  { id: 1, name: "Iron Man" },
  { id: 2, name: "Ant - Man" },
  { id: 3, name: "The Wasp" },
  { id: 4, name: "Hulk" },
  { id: 5, name: "Captain America" },
  { id: 6, name: "Hawkeye" },
  { id: 7, name: "Quicksilver" },
  { id: 8, name: "Scarlet Witch" },
  { id: 9, name: "Hercules" },
  { id: 10, name: "Black Panther" },
  { id: 11, name: "Black Knight" },
  { id: 12, name: "Black Widow" },
  { id: 13, name: "Swordsman" },
  { id: 14, name: "Mantis" },
  { id: 15, name: "Beast" },
  { id: 16, name: "Moondragon" },
  { id: 17, name: "Patsy Walker" },
  { id: 18, name: "Wonder Man" },
  { id: 19, name: "Two - Gun Kid" },
  { id: 20, name: "Ms.Marvel" },
  { id: 21, name: "Falcon" },
  { id: 22, name: "Tigra" },
  { id: 23, name: "She - Hulk" },
  { id: 24, name: "Captain Marvel" },
  { id: 25, name: "Starfox" },
  { id: 26, name: "Namor" },
  { id: 27, name: "Doctor Druid" },
  { id: 28, name: "Mockingbird" },
  { id: 29, name: "War Machine" },
  { id: 30, name: "Thing" },
  { id: 31, name: "Moon Knight" },
  { id: 32, name: "Firebird" },
  { id: 33, name: "Bonita Juárez" },
  { id: 34, name: "Human Torch" },
  { id: 35, name: "Living Lightning" },
  { id: 36, name: "Spider - Woman" },
  { id: 37, name: "X - 51" },
  { id: 38, name: "Darkhawk" },
  { id: 39, name: "Demolition Man" },
  { id: 40, name: "Forgotten One" },
  { id: 41, name: "Mister Fantastic" },
  { id: 42, name: "Invisible Woman" },
  { id: 43, name: "Quasar" },
  { id: 44, name: "Sersi" },
  { id: 45, name: "Stingray" },
  { id: 46, name: "Spider - Man" },
  { id: 47, name: "Sandman" },
  { id: 48, name: "Rage" },
  { id: 49, name: "Crystal" },
  { id: 50, name: "Thunderstrike" },
  { id: 51, name: "Justice" },
  { id: 52, name: "Firestar" },
  { id: 53, name: "Triathlon" },
  { id: 54, name: "Silverclaw" },
  { id: 55, name: "Jack of Hearts" },
  { id: 56, name: "Captain Britain" },
  { id: 57, name: "Luke Cage" },
  { id: 58, name: "Wolverine" },
  { id: 59, name: "Sentry" },
  { id: 60, name: "Echo" },
  { id: 61, name: "Ares" },
  { id: 62, name: "Amadeus Cho" },
  { id: 63, name: "Jocasta" },
  { id: 64, name: "Stature" },
  { id: 65, name: "Vision" },
  { id: 66, name: "Valkyrie" },
  { id: 67, name: "Nova" },
  { id: 68, name: "Sharon Carter" },
  { id: 69, name: "Iron Fist" },
  { id: 70, name: "Xorr the God- Jewe" },
  { id: 71, name: "Victoria Hand" },
  { id: 72, name: "Rick Jones" },
  { id: 73, name: "Captain Marvel" },
  { id: 74, name: "Whizzer" },
  { id: 75, name: "Yellowjacket" },
  { id: 76, name: "Magdalene" },
  { id: 77, name: "Deathcry" },
  { id: 78, name: "Moira Brandon" },
  { id: 79, name: "Masque" },
  { id: 80, name: "Doctor Strange" },
  { id: 81, name: "Yondu" },
  { id: 82, name: "Martinex" },
  { id: 83, name: "Nikki" },
  { id: 84, name: "Starhawk" },
  { id: 85, name: "Hawkeye" }
];

export default avengers;